enum ServiceCategory {
  streaming,
  realEstate,
  career,
  technology,
  gaming,
  shopping,
  foodDelivery,
  news,
  socialMedia,
  finance,
  insurance,
  travel,
  vehicles,
  comparison,
  email,
  shipping,
  betting,
  tickets,
  cloud,
  smartHome,
  newsletterSystem,
  health,
  telecommunications,
  marketplace,
  productivity,
  officeSupplies,
  surveys,
  unknown,
  other,
}

extension ServiceCategoryLabels on ServiceCategory {
  String get id => switch (this) {
    ServiceCategory.streaming => 'streaming',
    ServiceCategory.realEstate => 'real_estate',
    ServiceCategory.career => 'career',
    ServiceCategory.technology => 'technology',
    ServiceCategory.gaming => 'gaming',
    ServiceCategory.shopping => 'shopping',
    ServiceCategory.foodDelivery => 'food_delivery',
    ServiceCategory.news => 'news',
    ServiceCategory.socialMedia => 'social_media',
    ServiceCategory.finance => 'finance',
    ServiceCategory.insurance => 'insurance',
    ServiceCategory.travel => 'travel',
    ServiceCategory.vehicles => 'vehicles',
    ServiceCategory.comparison => 'comparison',
    ServiceCategory.email => 'email',
    ServiceCategory.shipping => 'shipping',
    ServiceCategory.betting => 'betting',
    ServiceCategory.tickets => 'tickets',
    ServiceCategory.cloud => 'cloud',
    ServiceCategory.smartHome => 'smart_home',
    ServiceCategory.newsletterSystem => 'newsletter_system',
    ServiceCategory.health => 'health',
    ServiceCategory.telecommunications => 'telecommunications',
    ServiceCategory.marketplace => 'marketplace',
    ServiceCategory.productivity => 'productivity',
    ServiceCategory.officeSupplies => 'office_supplies',
    ServiceCategory.surveys => 'surveys',
    ServiceCategory.unknown => 'unknown',
    ServiceCategory.other => 'other',
  };

  String get germanLabel => switch (this) {
    ServiceCategory.streaming => 'Streaming',
    ServiceCategory.realEstate => 'Immobilien',
    ServiceCategory.career => 'Karriere',
    ServiceCategory.technology => 'Technologie',
    ServiceCategory.gaming => 'Gaming',
    ServiceCategory.shopping => 'Shopping',
    ServiceCategory.foodDelivery => 'Essen & Lieferung',
    ServiceCategory.news => 'News & Medien',
    ServiceCategory.socialMedia => 'Social Media',
    ServiceCategory.finance => 'Finanzen',
    ServiceCategory.insurance => 'Versicherung',
    ServiceCategory.travel => 'Reisen',
    ServiceCategory.vehicles => 'Fahrzeuge',
    ServiceCategory.comparison => 'Vergleich',
    ServiceCategory.email => 'E-Mail',
    ServiceCategory.shipping => 'Versand',
    ServiceCategory.betting => 'Sportwetten',
    ServiceCategory.tickets => 'Tickets & Events',
    ServiceCategory.cloud => 'Cloud',
    ServiceCategory.smartHome => 'Smart Home',
    ServiceCategory.newsletterSystem => 'Newsletter-System',
    ServiceCategory.health => 'Gesundheit',
    ServiceCategory.telecommunications => 'Telekommunikation',
    ServiceCategory.marketplace => 'Marktplatz',
    ServiceCategory.productivity => 'Produktivität',
    ServiceCategory.officeSupplies => 'Bürobedarf',
    ServiceCategory.surveys => 'Umfragen',
    ServiceCategory.unknown => 'Unbekannt',
    ServiceCategory.other => 'Sonstiges',
  };
}

ServiceCategory serviceCategoryFromId(String id) =>
    ServiceCategory.values.firstWhere(
      (category) => category.id == id,
      orElse: () => ServiceCategory.unknown,
    );
